#! /bin/sh

# Autostart
mpd &
bash ~/.config/polybar/launch.sh --forest
xmodmap ~/.config/.Xmodmap
feh --bg-scale ~/Pictures/Unsplash/robin.jpg
sxhkd &
picom &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
# Config
bspc config border_width      2 
bspc config window_gap        3
#bspc config window_gap       0
bspc config left_padding	  2 
bspc config right_padding	  2
bspc config top_padding      27
bspc config bottom_padding	  2
bspc config normal_border_color   "#46494f"
bspc config focused_border_color  "#e24834"
xsetroot -cursor_name left_ptr
bspc config presel_feedback_color "#f4800d"

#Rules
bspc config split_ratio          0.5
bspc config borderless_monocle   false 
bspc config gapless_monocle      true 
bspc config pointer_modifier	 mod4
bspc config click_to_focus  	 false

bspc config focus_follows_pointer true
bspc monitor -d I II III IV V VI VII VIII IX X



# Window Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a nmtui state=floating

